package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReactionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionsAllPropertiesEquals(Reactions expected, Reactions actual) {
        assertReactionsAutoGeneratedPropertiesEquals(expected, actual);
        assertReactionsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionsAllUpdatablePropertiesEquals(Reactions expected, Reactions actual) {
        assertReactionsUpdatableFieldsEquals(expected, actual);
        assertReactionsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionsAutoGeneratedPropertiesEquals(Reactions expected, Reactions actual) {
        assertThat(expected)
            .as("Verify Reactions auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionsUpdatableFieldsEquals(Reactions expected, Reactions actual) {
        assertThat(expected)
            .as("Verify Reactions relevant properties")
            .satisfies(e -> assertThat(e.getReaction()).as("check reaction").isEqualTo(actual.getReaction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionsUpdatableRelationshipsEquals(Reactions expected, Reactions actual) {
        assertThat(expected)
            .as("Verify Reactions relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()))
            .satisfies(e -> assertThat(e.getMessages()).as("check messages").isEqualTo(actual.getMessages()));
    }
}
